on: [push]

jobs:
  binadox_job:
    runs-on: ubuntu-latest
    name: Binadox Structure-As-Code Analyzer
    steps:
      - name: binadox
        uses: binadox-public/binadox-infrastructure-as-code-analyzer@v1.2
        with:
          binadox-secret-token: '${{ secrets.BINADOX_TOKEN }}'
          binadox-server-url: 'https://qa1.binadox.com/api/1/organizations/pricing/callback/analyze_iaac'
          binadox-project-name: 'my project'
      - name: Get the status
        run: echo "Status ${{ steps.binadox.outputs.status }}"
